[package]
name = "advent-of-code-2021"
authors = ["Drew Wyatt <drew.j.wyatt@gmail.com>"]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[lib]
name = "advent"
path = "src/lib.rs"

[[bin]]
name = "day-1"

[dependencies]
